#!/bin/sh

#DEFINES="-DNK_INCLUDE_FIXED_TYPES=1"
#DEFINES="$DEFINES -DNK_INCLUDE_STANDARD_IO=1"
#DEFINES="$DEFINES -DNK_INCLUDE_STANDARD_VARARGS=1"
#DEFINES="$DEFINES -DNK_INCLUDE_DEFAULT_ALLOCATOR=1"
#DEFINES="$DEFINES -DNK_INCLUDE_VERTEX_BUFFER_OUTPUT=1"
#DEFINES="$DEFINES -DNK_INCLUDE_FONT_BAKING=1"
#DEFINES="$DEFINES -DNK_INCLUDE_DEFAULT_FONT=1"
#DEFINES="$DEFINES -DNK_IMPLEMENTATION=1"
#DEFINES="$DEFINES -DNK_SDL_GL2_IMPLEMENTATION=1"

INCLUDE_DIRS="-I$PWD/3rd_party/SDL2 -I$PWD/3rd_party/SDL2/include -I$PWD/3rd_party -I$PWD/3rd_party/nuklear" 
SOURCENAME="nuklear_sdl2_gl2_implementation"
SOURCES="$PWD/src/$SOURCENAME.c"
OBJS="$SOURCENAME.o"
COMP_FLAGS="-O2"
AR_FLAGS="rcs"
OUT_LIB="libnuklear_sdl2_gl2.a"

mkdir -p $PWD/lib; cd $PWD/lib
gcc -c $INCLUDE_DIRS $COMP_FLAGS $SOURCES
ar $AR_FLAGS $OUT_LIB $OBJS
cd ..
